version: '3'

services:
  php:
    build: ${DOCKER_ROOT}/php
    depends_on:
      - database
    working_dir: ${CONTAINERS_WORKDIR}
    volumes:
      - ${PHP_EXTERNAL_DIRECTORY}:${CONTAINERS_WORKDIR}
      - ${DOCKER_ROOT}/php/php.ini:/usr/local/etc/php/php.ini
  node:
    build: ${DOCKER_ROOT}/node
    command: ${NODE_COMMAND}
    working_dir: ${CONTAINERS_WORKDIR}
    volumes:
      - ${NODE_EXTERNAL_DIRECTORY}:${CONTAINERS_WORKDIR}
  nginx:
    image: nginx:latest
    depends_on:
      - php
      - node
    ports:
      - ${NGINX_EXTERNAL_PORT}:${NGINX_INTERNAL_PORT}
    working_dir: ${CONTAINERS_WORKDIR}
    volumes:
      - ${NGINX_EXTERNAL_DIRECTORY}:${CONTAINERS_WORKDIR}
      - ${DOCKER_ROOT}/nginx/:/etc/nginx/conf.d/
      - ${DOCKER_ROOT}/nginx/log:/var/log/nginx/
  database:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${DATABASE_DATABASE}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ${DOCKER_ROOT}/database:/var/lib/mysql
